using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NES_Core_CalorieCalculator.DataCore.Concretes;
using NES_Core_CalorieCalculator.DataCore.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NES_Core_CalorieCalculator.DAL.Configuration
{
    public class ConfigNutrient : IEntityTypeConfiguration<Nutrient>
    {
        public void Configure(EntityTypeBuilder<Nutrient> builder)
        {
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Name)
                .IsRequired(true)
                .HasColumnType("nvarchar(50)");

            builder.Property(x => x.Name)
                .IsRequired(true)
                .HasColumnType("nvarchar(50)");

            builder.Property(x => x.Calorie)
                .IsRequired(true)
                .HasColumnType("decimal(7,2)");

            builder.Property(x => x.Status)
                .IsRequired(true)
                .HasColumnType("nvarchar(10)");

            builder.Property(x => x.CreateDate)
                .IsRequired(true)
                .HasColumnType("date");

            builder.Property(x => x.DropDate)
                .IsRequired(false)
                .HasColumnType("date");

            //DataSeed
            //builder.HasData
            //    (
            //        new Nutrient { Id = 1, Name = "Peynir", Calorie = 24.2, NutrientNutrientCategoryId = 1, Status = Status.Created },
            //        new Nutrient { Id = 2, Name = "Süt", Calorie = 14.6, NutrientNutrientCategoryId = 2, Status = Status.Created },
            //        new Nutrient { Id = 3, Name = "Balık", Calorie = 34.1, NutrientNutrientCategoryId = 3, Status = Status.Created },
            //        new Nutrient { Id = 4, Name = "Dana Eti", Calorie = 22.3, NutrientNutrientCategoryId = 4, Status = Status.Created },
            //        new Nutrient { Id = 5, Name = "Tavuk Eti", Calorie = 11.3, NutrientNutrientCategoryId = 5, Status = Status.Created },
            //        new Nutrient { Id = 6, Name = "Kuzu Eti", Calorie = 55.3, NutrientNutrientCategoryId = 6, Status = Status.Created },
            //        new Nutrient { Id = 7, Name = "Karides", Calorie = 38.3, NutrientNutrientCategoryId = 7, Status = Status.Created },
            //        new Nutrient { Id = 8, Name = "Sütlaç", Calorie = 58.3, NutrientNutrientCategoryId = 8, Status = Status.Created },
            //        new Nutrient { Id = 9, Name = "Meyve Suyu Eti", Calorie = 21.3, NutrientNutrientCategoryId = 9, Status = Status.Created }
            //    );
            builder.HasData
        (
        new Nutrient { Id = 1, NutrientCategoryId = 1, Name = "Artichoke", Calorie = 60, Picture = "\\FoodPhotos\\1.jpg", Status = Status.Created },
        new Nutrient { Id = 2, NutrientCategoryId = 1, Name = "Arugula", Calorie = 50, Picture = "\\FoodPhotos\\2.jpg", Status = Status.Created },
        new Nutrient { Id = 3, NutrientCategoryId = 1, Name = "Asparagus", Calorie = 2, Picture = "\\FoodPhotos\\3.jpg", Status = Status.Created },
        new Nutrient { Id = 4, NutrientCategoryId = 1, Name = "Aubergine", Calorie = 115, Picture = "\\FoodPhotos\\4.jpg", Status = Status.Created },
        new Nutrient { Id = 5, NutrientCategoryId = 1, Name = "Beetroot", Calorie = 35, Picture = "\\FoodPhotos\\5.jpg", Status = Status.Created },
        new Nutrient { Id = 6, NutrientCategoryId = 1, Name = "Bell Pepper", Calorie = 15, Picture = "\\FoodPhotos\\6.jpg", Status = Status.Created },
        new Nutrient { Id = 7, NutrientCategoryId = 1, Name = "Black Olives", Calorie = 2, Picture = "\\FoodPhotos\\7.jpg", Status = Status.Created },
        new Nutrient { Id = 8, NutrientCategoryId = 1, Name = "Broccoli", Calorie = 35, Picture = "\\FoodPhotos\\8.jpg", Status = Status.Created },
        new Nutrient { Id = 9, NutrientCategoryId = 1, Name = "Brussels Sprouts", Calorie = 40, Picture = "\\FoodPhotos\\9.jpg", Status = Status.Created },
        new Nutrient { Id = 10, NutrientCategoryId = 1, Name = "Cabbage", Calorie = 227, Picture = "\\FoodPhotos\\10.jpg", Status = Status.Created },
        new Nutrient { Id = 11, NutrientCategoryId = 1, Name = "Capsicum", Calorie = 12, Picture = "\\FoodPhotos\\11.jpg", Status = Status.Created },
        new Nutrient { Id = 12, NutrientCategoryId = 1, Name = "Carrot", Calorie = 25, Picture = "\\FoodPhotos\\12.jpg", Status = Status.Created },
        new Nutrient { Id = 13, NutrientCategoryId = 1, Name = "Cauliflower", Calorie = 3, Picture = "\\FoodPhotos\\13.jpg", Status = Status.Created },
        new Nutrient { Id = 14, NutrientCategoryId = 1, Name = "Celery", Calorie = 42, Picture = "\\FoodPhotos\\14.jpg", Status = Status.Created },
        new Nutrient { Id = 15, NutrientCategoryId = 1, Name = "Cherry Tomato", Calorie = 20, Picture = "\\FoodPhotos\\15.jpg", Status = Status.Created },
        new Nutrient { Id = 16, NutrientCategoryId = 1, Name = "Chinese Cabbage", Calorie = 134, Picture = "\\FoodPhotos\\16.jpg", Status = Status.Created },
        new Nutrient { Id = 17, NutrientCategoryId = 1, Name = "Collard Greens", Calorie = 32, Picture = "\\FoodPhotos\\17.jpg", Status = Status.Created },
        new Nutrient { Id = 18, NutrientCategoryId = 1, Name = "Corn", Calorie = 96, Picture = "\\FoodPhotos\\18.jpg", Status = Status.Created },
        new Nutrient { Id = 19, NutrientCategoryId = 1, Name = "Courgette", Calorie = 20, Picture = "\\FoodPhotos\\19.jpg", Status = Status.Created },
        new Nutrient { Id = 20, NutrientCategoryId = 1, Name = "Cucumber", Calorie = 15, Picture = "\\FoodPhotos\\20.jpg", Status = Status.Created },
        new Nutrient { Id = 21, NutrientCategoryId = 11, Name = "Salami", Calorie = 336, Picture = "\\FoodPhotos\\21.jpg", Status = Status.Created },
        new Nutrient { Id = 22, NutrientCategoryId = 1, Name = "Endive", Calorie = 17, Picture = "\\FoodPhotos\\22.jpg", Status = Status.Created },
        new Nutrient { Id = 23, NutrientCategoryId = 1, Name = "Fennel", Calorie = 32, Picture = "\\FoodPhotos\\23.jpg", Status = Status.Created },
        new Nutrient { Id = 24, NutrientCategoryId = 1, Name = "Garlic", Calorie = 4, Picture = "\\FoodPhotos\\24.jpg", Status = Status.Created },
        new Nutrient { Id = 25, NutrientCategoryId = 1, Name = "Gherkin", Calorie = 9, Picture = "\\FoodPhotos\\25.jpg", Status = Status.Created },
        new Nutrient { Id = 26, NutrientCategoryId = 1, Name = "Gourd", Calorie = 108, Picture = "\\FoodPhotos\\26.jpg", Status = Status.Created },
        new Nutrient { Id = 27, NutrientCategoryId = 1, Name = "Green Beans", Calorie = 32, Picture = "\\FoodPhotos\\27.jpg", Status = Status.Created },
        new Nutrient { Id = 28, NutrientCategoryId = 1, Name = "Green Olives", Calorie = 2, Picture = "\\FoodPhotos\\28.jpg", Status = Status.Created },
        new Nutrient { Id = 29, NutrientCategoryId = 1, Name = "Green Onion", Calorie = 5, Picture = "\\FoodPhotos\\29.jpg", Status = Status.Created },
        new Nutrient { Id = 30, NutrientCategoryId = 1, Name = "Horseradish", Calorie = 7, Picture = "\\FoodPhotos\\30.jpg", Status = Status.Created },
        new Nutrient { Id = 31, NutrientCategoryId = 1, Name = "Kale", Calorie = 43, Picture = "\\FoodPhotos\\31.jpg", Status = Status.Created },
        new Nutrient { Id = 32, NutrientCategoryId = 1, Name = "Leek", Calorie = 54, Picture = "\\FoodPhotos\\32.jpg", Status = Status.Created },
        new Nutrient { Id = 33, NutrientCategoryId = 1, Name = "Lettuce", Calorie = 109, Picture = "\\FoodPhotos\\33.jpg", Status = Status.Created },
        new Nutrient { Id = 34, NutrientCategoryId = 1, Name = "Mushrooms", Calorie = 1, Picture = "\\FoodPhotos\\34.jpg", Status = Status.Created },
        new Nutrient { Id = 35, NutrientCategoryId = 1, Name = "Mustard Greens", Calorie = 28, Picture = "\\FoodPhotos\\35.jpg", Status = Status.Created },
        new Nutrient { Id = 36, NutrientCategoryId = 1, Name = "Okra", Calorie = 33, Picture = "\\FoodPhotos\\36.jpg", Status = Status.Created },
        new Nutrient { Id = 37, NutrientCategoryId = 11, Name = "Sausage", Calorie = 300, Picture = "\\FoodPhotos\\37.jpg", Status = Status.Created },
        new Nutrient { Id = 38, NutrientCategoryId = 1, Name = "Onion", Calorie = 34, Picture = "\\FoodPhotos\\38.jpg", Status = Status.Created },
        new Nutrient { Id = 39, NutrientCategoryId = 1, Name = "Parsnips", Calorie = 128, Picture = "\\FoodPhotos\\39.jpg", Status = Status.Created },
        new Nutrient { Id = 40, NutrientCategoryId = 1, Name = "Peas", Calorie = 81, Picture = "\\FoodPhotos\\40.jpg", Status = Status.Created },
        new Nutrient { Id = 41, NutrientCategoryId = 11, Name = "Bacon", Calorie = 29, Picture = "\\FoodPhotos\\41.jpg", Status = Status.Created },
        new Nutrient { Id = 42, NutrientCategoryId = 1, Name = "Potato", Calorie = 164, Picture = "\\FoodPhotos\\42.jpg", Status = Status.Created },
        new Nutrient { Id = 43, NutrientCategoryId = 1, Name = "Pumpkin", Calorie = 51, Picture = "\\FoodPhotos\\43.jpg", Status = Status.Created },
        new Nutrient { Id = 44, NutrientCategoryId = 1, Name = "Radishes", Calorie = 15, Picture = "\\FoodPhotos\\44.jpg", Status = Status.Created },
        new Nutrient { Id = 45, NutrientCategoryId = 1, Name = "Red Cabbage", Calorie = 260, Picture = "\\FoodPhotos\\45.jpg", Status = Status.Created },
        new Nutrient { Id = 46, NutrientCategoryId = 1, Name = "Rutabaga", Calorie = 147, Picture = "\\FoodPhotos\\46.jpg", Status = Status.Created },
        new Nutrient { Id = 47, NutrientCategoryId = 1, Name = "Shallots", Calorie = 18, Picture = "\\FoodPhotos\\47.jpg", Status = Status.Created },
        new Nutrient { Id = 48, NutrientCategoryId = 1, Name = "Squash", Calorie = 130, Picture = "\\FoodPhotos\\48.jpg", Status = Status.Created },
        new Nutrient { Id = 49, NutrientCategoryId = 1, Name = "Sweet Potato", Calorie = 112, Picture = "\\FoodPhotos\\49.jpg", Status = Status.Created },
        new Nutrient { Id = 50, NutrientCategoryId = 1, Name = "Tomato", Calorie = 20, Picture = "\\FoodPhotos\\50.jpg", Status = Status.Created },
        new Nutrient { Id = 51, NutrientCategoryId = 1, Name = "Turnip", Calorie = 34, Picture = "\\FoodPhotos\\51.jpg", Status = Status.Created },
        new Nutrient { Id = 52, NutrientCategoryId = 2, Name = "Apple", Calorie = 95, Picture = "\\FoodPhotos\\52.jpg", Status = Status.Created },
        new Nutrient { Id = 53, NutrientCategoryId = 2, Name = "Apricot", Calorie = 17, Picture = "\\FoodPhotos\\53.jpg", Status = Status.Created },
        new Nutrient { Id = 54, NutrientCategoryId = 2, Name = "Avocado", Calorie = 240, Picture = "\\FoodPhotos\\54.jpg", Status = Status.Created },
        new Nutrient { Id = 55, NutrientCategoryId = 2, Name = "Banana", Calorie = 111, Picture = "\\FoodPhotos\\55.jpg", Status = Status.Created },
        new Nutrient { Id = 56, NutrientCategoryId = 2, Name = "Blackberries", Calorie = 43, Picture = "\\FoodPhotos\\56.jpg", Status = Status.Created },
        new Nutrient { Id = 57, NutrientCategoryId = 2, Name = "Blood Oranges", Calorie = 70, Picture = "\\FoodPhotos\\57.jpg", Status = Status.Created },
        new Nutrient { Id = 58, NutrientCategoryId = 2, Name = "Blueberries", Calorie = 84, Picture = "\\FoodPhotos\\58.jpg", Status = Status.Created },
        new Nutrient { Id = 59, NutrientCategoryId = 2, Name = "Cantaloupe", Calorie = 34, Picture = "\\FoodPhotos\\59.jpg", Status = Status.Created },
        new Nutrient { Id = 60, NutrientCategoryId = 2, Name = "Cherries", Calorie = 4, Picture = "\\FoodPhotos\\60.jpg", Status = Status.Created },
        new Nutrient { Id = 61, NutrientCategoryId = 2, Name = "Cranberries", Calorie = 46, Picture = "\\FoodPhotos\\61.jpg", Status = Status.Created },
        new Nutrient { Id = 62, NutrientCategoryId = 2, Name = "Dates", Calorie = 20, Picture = "\\FoodPhotos\\62.jpg", Status = Status.Created },
        new Nutrient { Id = 63, NutrientCategoryId = 2, Name = "Figs", Calorie = 37, Picture = "\\FoodPhotos\\63.jpg", Status = Status.Created },
        new Nutrient { Id = 64, NutrientCategoryId = 7, Name = "Fruit salad", Calorie = 125, Picture = "\\FoodPhotos\\64.jpg", Status = Status.Created },
        new Nutrient { Id = 65, NutrientCategoryId = 2, Name = "Grapes", Calorie = 67, Picture = "\\FoodPhotos\\65.jpg", Status = Status.Created },
        new Nutrient { Id = 66, NutrientCategoryId = 2, Name = "Kiwi", Calorie = 112, Picture = "\\FoodPhotos\\66.jpg", Status = Status.Created },
        new Nutrient { Id = 67, NutrientCategoryId = 2, Name = "Lemon", Calorie = 17, Picture = "\\FoodPhotos\\67.jpg", Status = Status.Created },
        new Nutrient { Id = 68, NutrientCategoryId = 2, Name = "Lime", Calorie = 20, Picture = "\\FoodPhotos\\68.jpg", Status = Status.Created },
        new Nutrient { Id = 69, NutrientCategoryId = 2, Name = "Lychees", Calorie = 7, Picture = "\\FoodPhotos\\69.jpg", Status = Status.Created },
        new Nutrient { Id = 70, NutrientCategoryId = 2, Name = "Mandarin Oranges", Calorie = 47, Picture = "\\FoodPhotos\\70.jpg", Status = Status.Created },
        new Nutrient { Id = 71, NutrientCategoryId = 2, Name = "Mango", Calorie = 202, Picture = "\\FoodPhotos\\71.jpg", Status = Status.Created },
        new Nutrient { Id = 72, NutrientCategoryId = 2, Name = "Nectarine", Calorie = 66, Picture = "\\FoodPhotos\\72.jpg", Status = Status.Created },
        new Nutrient { Id = 73, NutrientCategoryId = 2, Name = "Orange", Calorie = 62, Picture = "\\FoodPhotos\\73.jpg", Status = Status.Created },
        new Nutrient { Id = 74, NutrientCategoryId = 2, Name = "Papaya", Calorie = 215, Picture = "\\FoodPhotos\\74.jpg", Status = Status.Created },
        new Nutrient { Id = 75, NutrientCategoryId = 2, Name = "Passion Fruit", Calorie = 17, Picture = "\\FoodPhotos\\75.jpg", Status = Status.Created },
        new Nutrient { Id = 76, NutrientCategoryId = 2, Name = "Peach", Calorie = 59, Picture = "\\FoodPhotos\\76.jpg", Status = Status.Created },
        new Nutrient { Id = 77, NutrientCategoryId = 2, Name = "Pear", Calorie = 101, Picture = "\\FoodPhotos\\77.jpg", Status = Status.Created },
        new Nutrient { Id = 78, NutrientCategoryId = 2, Name = "Pineapple", Calorie = 50, Picture = "\\FoodPhotos\\78.jpg", Status = Status.Created },
        new Nutrient { Id = 79, NutrientCategoryId = 2, Name = "Plum", Calorie = 30, Picture = "\\FoodPhotos\\79.jpg", Status = Status.Created },
        new Nutrient { Id = 80, NutrientCategoryId = 2, Name = "Pomegranate", Calorie = 234, Picture = "\\FoodPhotos\\80.jpg", Status = Status.Created },
        new Nutrient { Id = 81, NutrientCategoryId = 5, Name = "Raisins", Calorie = 300, Picture = "\\FoodPhotos\\81.jpg", Status = Status.Created },
        new Nutrient { Id = 82, NutrientCategoryId = 2, Name = "Raspberries", Calorie = 64, Picture = "\\FoodPhotos\\82.jpg", Status = Status.Created },
        new Nutrient { Id = 83, NutrientCategoryId = 2, Name = "Strawberries", Calorie = 49, Picture = "\\FoodPhotos\\83.jpg", Status = Status.Created },
        new Nutrient { Id = 84, NutrientCategoryId = 2, Name = "Tangerine", Calorie = 47, Picture = "\\FoodPhotos\\84.jpg", Status = Status.Created },
        new Nutrient { Id = 85, NutrientCategoryId = 2, Name = "Watermelon", Calorie = 86, Picture = "\\FoodPhotos\\85.jpg", Status = Status.Created },
        new Nutrient { Id = 86, NutrientCategoryId = 8, Name = "Bacon and Eggs", Calorie = 680, Picture = "\\FoodPhotos\\86.jpg", Status = Status.Created },
        new Nutrient { Id = 87, NutrientCategoryId = 12, Name = "Baked Beans", Calorie = 150, Picture = "\\FoodPhotos\\87.jpg", Status = Status.Created },
        new Nutrient { Id = 88, NutrientCategoryId = 11, Name = "BBQ Ribs", Calorie = 360, Picture = "\\FoodPhotos\\88.jpg", Status = Status.Created },
        new Nutrient { Id = 89, NutrientCategoryId = 11, Name = "Beef Stew", Calorie = 186, Picture = "\\FoodPhotos\\89.jpg", Status = Status.Created },
        new Nutrient { Id = 90, NutrientCategoryId = 12, Name = "Black Rice", Calorie = 170, Picture = "\\FoodPhotos\\90.jpg", Status = Status.Created },
        new Nutrient { Id = 91, NutrientCategoryId = 12, Name = "Brown Rice", Calorie = 110, Picture = "\\FoodPhotos\\91.jpg", Status = Status.Created },
        new Nutrient { Id = 92, NutrientCategoryId = 10, Name = "Burrito", Calorie = 326, Picture = "\\FoodPhotos\\92.jpg", Status = Status.Created },
        new Nutrient { Id = 93, NutrientCategoryId = 9, Name = "California Roll", Calorie = 33, Picture = "\\FoodPhotos\\93.jpg", Status = Status.Created },
        new Nutrient { Id = 94, NutrientCategoryId = 7, Name = "Chicken Caesar Salad", Calorie = 309, Picture = "\\FoodPhotos\\94.jpg", Status = Status.Created },
        new Nutrient { Id = 95, NutrientCategoryId = 11, Name = "Chicken Marsala", Calorie = 290, Picture = "\\FoodPhotos\\95.jpg", Status = Status.Created },
        new Nutrient { Id = 96, NutrientCategoryId = 11, Name = "Chicken Tikka Masala", Calorie = 350, Picture = "\\FoodPhotos\\96.jpg", Status = Status.Created },
        new Nutrient { Id = 97, NutrientCategoryId = 11, Name = "Chimichanga", Calorie = 308, Picture = "\\FoodPhotos\\97.jpg", Status = Status.Created },
        new Nutrient { Id = 98, NutrientCategoryId = 7, Name = "Cobb Salad", Calorie = 160, Picture = "\\FoodPhotos\\98.jpg", Status = Status.Created },
        new Nutrient { Id = 99, NutrientCategoryId = 10, Name = "Corn Dog", Calorie = 180, Picture = "\\FoodPhotos\\99.jpg", Status = Status.Created },
        new Nutrient { Id = 100, NutrientCategoryId = 6, Name = "Cottage Pie", Calorie = 300, Picture = "\\FoodPhotos\\100.jpg", Status = Status.Created },
        new Nutrient { Id = 101, NutrientCategoryId = 11, Name = "Enchiladas", Calorie = 323, Picture = "\\FoodPhotos\\101.jpg", Status = Status.Created },
        new Nutrient { Id = 102, NutrientCategoryId = 11, Name = "Fajita", Calorie = 290, Picture = "\\FoodPhotos\\102.jpg", Status = Status.Created },
        new Nutrient { Id = 103, NutrientCategoryId = 9, Name = "Fish and Chips", Calorie = 585, Picture = "\\FoodPhotos\\103.jpg", Status = Status.Created },
        new Nutrient { Id = 104, NutrientCategoryId = 12, Name = "Fried Rice", Calorie = 662, Picture = "\\FoodPhotos\\104.jpg", Status = Status.Created },
        new Nutrient { Id = 105, NutrientCategoryId = 9, Name = "Fried Shrimp", Calorie = 75, Picture = "\\FoodPhotos\\105.jpg", Status = Status.Created },
        new Nutrient { Id = 106, NutrientCategoryId = 10, Name = "Grilled Cheese Sandwich", Calorie = 392, Picture = "\\FoodPhotos\\106.jpg", Status = Status.Created },
        new Nutrient { Id = 107, NutrientCategoryId = 10, Name = "Ham and Cheese Sandwich", Calorie = 352, Picture = "\\FoodPhotos\\107.jpg", Status = Status.Created },
        new Nutrient { Id = 108, NutrientCategoryId = 11, Name = "Kebab", Calorie = 774, Picture = "\\FoodPhotos\\108.jpg", Status = Status.Created },
        new Nutrient { Id = 109, NutrientCategoryId = 10, Name = "Lasagne", Calorie = 284, Picture = "\\FoodPhotos\\109.jpg", Status = Status.Created },
        new Nutrient { Id = 110, NutrientCategoryId = 10, Name = "Mac and Cheese", Calorie = 699, Picture = "\\FoodPhotos\\110.jpg", Status = Status.Created },
        new Nutrient { Id = 111, NutrientCategoryId = 11, Name = "Orange Chicken", Calorie = 420, Picture = "\\FoodPhotos\\111.jpg", Status = Status.Created },
        new Nutrient { Id = 112, NutrientCategoryId = 10, Name = "Pad Thai", Calorie = 375, Picture = "\\FoodPhotos\\112.jpg", Status = Status.Created },
        new Nutrient { Id = 113, NutrientCategoryId = 13, Name = "Pea Soup", Calorie = 190, Picture = "\\FoodPhotos\\113.jpg", Status = Status.Created },
        new Nutrient { Id = 114, NutrientCategoryId = 10, Name = "Peanut Butter Sandwich", Calorie = 200, Picture = "\\FoodPhotos\\114.jpg", Status = Status.Created },
        new Nutrient { Id = 115, NutrientCategoryId = 11, Name = "Philly Cheese Steak", Calorie = 300, Picture = "\\FoodPhotos\\115.jpg", Status = Status.Created },
        new Nutrient { Id = 116, NutrientCategoryId = 10, Name = "Pizza", Calorie = 272, Picture = "\\FoodPhotos\\116.jpg", Status = Status.Created },
        new Nutrient { Id = 117, NutrientCategoryId = 7, Name = "Potato Salad", Calorie = 300, Picture = "\\FoodPhotos\\117.jpg", Status = Status.Created },
        new Nutrient { Id = 118, NutrientCategoryId = 10, Name = "Ramen", Calorie = 500, Picture = "\\FoodPhotos\\118.jpg", Status = Status.Created },
        new Nutrient { Id = 119, NutrientCategoryId = 10, Name = "Ravioli", Calorie = 370, Picture = "\\FoodPhotos\\119.jpg", Status = Status.Created },
        new Nutrient { Id = 120, NutrientCategoryId = 10, Name = "Reuben Sandwich", Calorie = 641, Picture = "\\FoodPhotos\\120.jpg", Status = Status.Created },
        new Nutrient { Id = 121, NutrientCategoryId = 11, Name = "Roast Beef", Calorie = 110, Picture = "\\FoodPhotos\\121.jpg", Status = Status.Created },
        new Nutrient { Id = 122, NutrientCategoryId = 10, Name = "Spaghetti Bolognese", Calorie = 374, Picture = "\\FoodPhotos\\122.jpg", Status = Status.Created },
        new Nutrient { Id = 123, NutrientCategoryId = 10, Name = "Taco", Calorie = 213, Picture = "\\FoodPhotos\\123.jpg", Status = Status.Created },
        new Nutrient { Id = 124, NutrientCategoryId = 10, Name = "BBQ Chicken Pizza", Calorie = 309, Picture = "\\FoodPhotos\\124.jpg", Status = Status.Created },
        new Nutrient { Id = 125, NutrientCategoryId = 10, Name = "BBQ Pizza", Calorie = 314, Picture = "\\FoodPhotos\\125.jpg", Status = Status.Created },
        new Nutrient { Id = 126, NutrientCategoryId = 10, Name = "Beef Pizza", Calorie = 714, Picture = "\\FoodPhotos\\126.jpg", Status = Status.Created },
        new Nutrient { Id = 127, NutrientCategoryId = 10, Name = "Bianca Pizza", Calorie = 460, Picture = "\\FoodPhotos\\127.jpg", Status = Status.Created },
        new Nutrient { Id = 128, NutrientCategoryId = 10, Name = "Buffalo Chicken Pizza", Calorie = 600, Picture = "\\FoodPhotos\\128.jpg", Status = Status.Created },
        new Nutrient { Id = 129, NutrientCategoryId = 10, Name = "Cheese Pizza", Calorie = 168, Picture = "\\FoodPhotos\\129.jpg", Status = Status.Created },
        new Nutrient { Id = 130, NutrientCategoryId = 10, Name = "Chicken Pizza", Calorie = 309, Picture = "\\FoodPhotos\\130.jpg", Status = Status.Created },
        new Nutrient { Id = 131, NutrientCategoryId = 10, Name = "Deep Dish Pizza", Calorie = 313, Picture = "\\FoodPhotos\\131.jpg", Status = Status.Created },
        new Nutrient { Id = 132, NutrientCategoryId = 10, Name = "Goat Cheese Pizza", Calorie = 138, Picture = "\\FoodPhotos\\132.jpg", Status = Status.Created },
        new Nutrient { Id = 133, NutrientCategoryId = 10, Name = "Grilled Pizza", Calorie = 280, Picture = "\\FoodPhotos\\133.jpg", Status = Status.Created },
        new Nutrient { Id = 134, NutrientCategoryId = 10, Name = "Hawaiian Pizza", Calorie = 154, Picture = "\\FoodPhotos\\134.jpg", Status = Status.Created },
        new Nutrient { Id = 135, NutrientCategoryId = 10, Name = "Margherita Pizza", Calorie = 173, Picture = "\\FoodPhotos\\135.jpg", Status = Status.Created },
        new Nutrient { Id = 136, NutrientCategoryId = 10, Name = "Mozzarella Pizza", Calorie = 154, Picture = "\\FoodPhotos\\136.jpg", Status = Status.Created },
        new Nutrient { Id = 137, NutrientCategoryId = 10, Name = "Mushroom Pizza", Calorie = 611, Picture = "\\FoodPhotos\\137.jpg", Status = Status.Created },
        new Nutrient { Id = 138, NutrientCategoryId = 10, Name = "Napoli Pizza", Calorie = 248, Picture = "\\FoodPhotos\\138.jpg", Status = Status.Created },
        new Nutrient { Id = 139, NutrientCategoryId = 10, Name = "New York Style Pizza", Calorie = 174, Picture = "\\FoodPhotos\\139.jpg", Status = Status.Created },
        new Nutrient { Id = 140, NutrientCategoryId = 10, Name = "Pepperoni Pizza", Calorie = 181, Picture = "\\FoodPhotos\\140.jpg", Status = Status.Created },
        new Nutrient { Id = 141, NutrientCategoryId = 10, Name = "Pizza Hut Stuffed Crust Pizza", Calorie = 380, Picture = "\\FoodPhotos\\141.jpg", Status = Status.Created },
        new Nutrient { Id = 142, NutrientCategoryId = 10, Name = "Pizza Hut Supreme Pizza", Calorie = 305, Picture = "\\FoodPhotos\\142.jpg", Status = Status.Created },
        new Nutrient { Id = 143, NutrientCategoryId = 10, Name = "Quattro Formaggi Pizza", Calorie = 330, Picture = "\\FoodPhotos\\143.jpg", Status = Status.Created },
        new Nutrient { Id = 144, NutrientCategoryId = 10, Name = "Red Pepper Pizza", Calorie = 165, Picture = "\\FoodPhotos\\144.jpg", Status = Status.Created },
        new Nutrient { Id = 145, NutrientCategoryId = 10, Name = "Salami Pizza", Calorie = 181, Picture = "\\FoodPhotos\\145.jpg", Status = Status.Created },
        new Nutrient { Id = 146, NutrientCategoryId = 10, Name = "Sausage Pizza", Calorie = 177, Picture = "\\FoodPhotos\\146.jpg", Status = Status.Created },
        new Nutrient { Id = 147, NutrientCategoryId = 10, Name = "Seafood Pizza", Calorie = 186, Picture = "\\FoodPhotos\\147.jpg", Status = Status.Created },
        new Nutrient { Id = 148, NutrientCategoryId = 10, Name = "Shrimp Pizza", Calorie = 190, Picture = "\\FoodPhotos\\148.jpg", Status = Status.Created },
        new Nutrient { Id = 149, NutrientCategoryId = 10, Name = "Sicilian Pizza", Calorie = 321, Picture = "\\FoodPhotos\\149.jpg", Status = Status.Created },
        new Nutrient { Id = 150, NutrientCategoryId = 10, Name = "Spinach Feta Pizza", Calorie = 150, Picture = "\\FoodPhotos\\150.jpg", Status = Status.Created },
        new Nutrient { Id = 151, NutrientCategoryId = 10, Name = "Spinach Pizza", Calorie = 145, Picture = "\\FoodPhotos\\151.jpg", Status = Status.Created },
        new Nutrient { Id = 152, NutrientCategoryId = 10, Name = "Stuffed Crust Pizza", Calorie = 380, Picture = "\\FoodPhotos\\152.jpg", Status = Status.Created },
        new Nutrient { Id = 153, NutrientCategoryId = 10, Name = "Thin Crust Pizza", Calorie = 157, Picture = "\\FoodPhotos\\153.jpg", Status = Status.Created },
        new Nutrient { Id = 154, NutrientCategoryId = 10, Name = "Tuna Pizza", Calorie = 318, Picture = "\\FoodPhotos\\154.jpg", Status = Status.Created },
        new Nutrient { Id = 155, NutrientCategoryId = 10, Name = "Veggie Pizza", Calorie = 263, Picture = "\\FoodPhotos\\155.jpg", Status = Status.Created },
        new Nutrient { Id = 156, NutrientCategoryId = 10, Name = "Burger King Angry Whopper", Calorie = 740, Picture = "\\FoodPhotos\\156.jpg", Status = Status.Created },
        new Nutrient { Id = 157, NutrientCategoryId = 10, Name = "Burger King Double Whopper", Calorie = 894, Picture = "\\FoodPhotos\\157.jpg", Status = Status.Created },
        new Nutrient { Id = 158, NutrientCategoryId = 10, Name = "Burger King Double Whopper with Cheese", Calorie = 994, Picture = "\\FoodPhotos\\158.jpg", Status = Status.Created },
        new Nutrient { Id = 159, NutrientCategoryId = 10, Name = "Burger King Original Chicken Sandwich", Calorie = 659, Picture = "\\FoodPhotos\\159.jpg", Status = Status.Created },
        new Nutrient { Id = 160, NutrientCategoryId = 10, Name = "Burger King Premium Alaskan Fish Sandwich", Calorie = 591, Picture = "\\FoodPhotos\\160.jpg", Status = Status.Created },
        new Nutrient { Id = 161, NutrientCategoryId = 10, Name = "Burger King Triple Whopper", Calorie = 1471, Picture = "\\FoodPhotos\\161.jpg", Status = Status.Created },
        new Nutrient { Id = 162, NutrientCategoryId = 10, Name = "Burger King Whopper", Calorie = 6272, Picture = "\\FoodPhotos\\162.jpg", Status = Status.Created },
        new Nutrient { Id = 163, NutrientCategoryId = 10, Name = "Burger King Whopper Jr.", Calorie = 346, Picture = "\\FoodPhotos\\163.jpg", Status = Status.Created },
        new Nutrient { Id = 164, NutrientCategoryId = 10, Name = "Burger King Whopper with Cheese", Calorie = 759, Picture = "\\FoodPhotos\\164.jpg", Status = Status.Created },
        new Nutrient { Id = 165, NutrientCategoryId = 10, Name = "Cheeseburger", Calorie = 410, Picture = "\\FoodPhotos\\165.jpg", Status = Status.Created },
        new Nutrient { Id = 166, NutrientCategoryId = 11, Name = "Chicken Breast", Calorie = 170, Picture = "\\FoodPhotos\\166.jpg", Status = Status.Created },
            new Nutrient { Id = 167, NutrientCategoryId = 10, Name = "Chicken Nuggets", Calorie = 59, Picture = "\\FoodPhotos\\167.jpg", Status = Status.Created },
            new Nutrient { Id = 168, NutrientCategoryId = 10, Name = "Chicken Sandwich", Calorie = 410, Picture = "\\FoodPhotos\\168.jpg", Status = Status.Created },
            new Nutrient { Id = 169, NutrientCategoryId = 10, Name = "Chicken Teriyaki Sandwich", Calorie = 367, Picture = "\\FoodPhotos\\169.jpg", Status = Status.Created },
            new Nutrient { Id = 170, NutrientCategoryId = 10, Name = "Chicken Wings", Calorie = 94, Picture = "\\FoodPhotos\\170.jpg", Status = Status.Created },
            new Nutrient { Id = 171, NutrientCategoryId = 10, Name = "Curly Fries", Calorie = 398, Picture = "\\FoodPhotos\\171.jpg", Status = Status.Created },
            new Nutrient { Id = 172, NutrientCategoryId = 10, Name = "Double Cheeseburger", Calorie = 414, Picture = "\\FoodPhotos\\172.jpg", Status = Status.Created },
            new Nutrient { Id = 173, NutrientCategoryId = 10, Name = "French Fries", Calorie = 222, Picture = "\\FoodPhotos\\173.jpg", Status = Status.Created },
            new Nutrient { Id = 174, NutrientCategoryId = 7, Name = "Grilled Chicken Salad", Calorie = 268, Picture = "\\FoodPhotos\\174.jpg", Status = Status.Created },
            new Nutrient { Id = 175, NutrientCategoryId = 10, Name = "Hamburger", Calorie = 279, Picture = "\\FoodPhotos\\175.jpg", Status = Status.Created },
            new Nutrient { Id = 176, NutrientCategoryId = 10, Name = "Hot Dog", Calorie = 312, Picture = "\\FoodPhotos\\176.jpg", Status = Status.Created },
            new Nutrient { Id = 177, NutrientCategoryId = 10, Name = "Meatball Sandwich", Calorie = 481, Picture = "\\FoodPhotos\\177.jpg", Status = Status.Created },
            new Nutrient { Id = 178, NutrientCategoryId = 10, Name = "Onion Rings", Calorie = 25, Picture = "\\FoodPhotos\\178.jpg", Status = Status.Created },
            new Nutrient { Id = 179, NutrientCategoryId = 9, Name = "Smoked Salmon", Calorie = 195, Picture = "\\FoodPhotos\\179.jpg", Status = Status.Created },
            new Nutrient { Id = 180, NutrientCategoryId = 10, Name = "Subway Club Sandwich", Calorie = 312, Picture = "\\FoodPhotos\\180.jpg", Status = Status.Created },
            new Nutrient { Id = 181, NutrientCategoryId = 10, Name = "Tortilla Wrap", Calorie = 171, Picture = "\\FoodPhotos\\181.jpg", Status = Status.Created },
            new Nutrient { Id = 182, NutrientCategoryId = 9, Name = "Tuna", Calorie = 94, Picture = "\\FoodPhotos\\182.jpg", Status = Status.Created },
            new Nutrient { Id = 183, NutrientCategoryId = 11, Name = "Turkey", Calorie = 135, Picture = "\\FoodPhotos\\183.jpg", Status = Status.Created },
            new Nutrient { Id = 184, NutrientCategoryId = 10, Name = "Veggie Burger", Calorie = 389, Picture = "\\FoodPhotos\\184.jpg", Status = Status.Created },
            new Nutrient { Id = 185, NutrientCategoryId = 10, Name = "Zinger", Calorie = 517, Picture = "\\FoodPhotos\\185.jpg", Status = Status.Created },
            new Nutrient { Id = 186, NutrientCategoryId = 11, Name = "Egg", Calorie = 68, Picture = "\\FoodPhotos\\186.jpg", Status = Status.Created },
            new Nutrient { Id = 187, NutrientCategoryId = 11, Name = "Steak", Calorie = 160, Picture = "\\FoodPhotos\\187.jpg", Status = Status.Created },
            new Nutrient { Id = 188, NutrientCategoryId = 13, Name = "Cornflakes", Calorie = 375, Picture = "\\FoodPhotos\\188.jpg", Status = Status.Created },
            new Nutrient { Id = 189, NutrientCategoryId = 6, Name = "Ice Cream Vanilla", Calorie = 135, Picture = "\\FoodPhotos\\189.jpg", Status = Status.Created },
            new Nutrient { Id = 190, NutrientCategoryId = 6, Name = "Ice Cream Chocolate", Calorie = 168, Picture = "\\FoodPhotos\\190.jpg", Status = Status.Created },
            new Nutrient { Id = 191, NutrientCategoryId = 5, Name = "Frozen Yogurt", Calorie = 135, Picture = "\\FoodPhotos\\191.jpg", Status = Status.Created },
            new Nutrient { Id = 192, NutrientCategoryId = 8, Name = "Yogurt", Calorie = 60, Picture = "\\FoodPhotos\\192.jpg", Status = Status.Created },
            new Nutrient { Id = 193, NutrientCategoryId = 6, Name = "Eclair", Calorie = 235, Picture = "\\FoodPhotos\\193.jpg", Status = Status.Created },
            new Nutrient { Id = 194, NutrientCategoryId = 3, Name = "Milkshake", Calorie = 350, Picture = "\\FoodPhotos\\194.jpg", Status = Status.Created },
            new Nutrient { Id = 195, NutrientCategoryId = 3, Name = "Milkshake Chocolate", Calorie = 400, Picture = "\\FoodPhotos\\195.jpg", Status = Status.Created },
            new Nutrient { Id = 196, NutrientCategoryId = 11, Name = "Pepperoni", Calorie = 550, Picture = "\\FoodPhotos\\196.jpg", Status = Status.Created },
            new Nutrient { Id = 197, NutrientCategoryId = 6, Name = "Macarons", Calorie = 55, Picture = "\\FoodPhotos\\197.jpg", Status = Status.Created },
            new Nutrient { Id = 198, NutrientCategoryId = 13, Name = "Bread", Calorie = 75, Picture = "\\FoodPhotos\\198.jpg", Status = Status.Created },
            new Nutrient { Id = 199, NutrientCategoryId = 6, Name = "Doughnut", Calorie = 230, Picture = "\\FoodPhotos\\199.jpg", Status = Status.Created },
            new Nutrient { Id = 200, NutrientCategoryId = 6, Name = "Doughnut Chocolate", Calorie = 380, Picture = "\\FoodPhotos\\200.jpg", Status = Status.Created },
            new Nutrient { Id = 201, NutrientCategoryId = 3, Name = "Tea", Calorie = 2, Picture = "\\FoodPhotos\\201.jpg", Status = Status.Created },
            new Nutrient { Id = 202, NutrientCategoryId = 13, Name = "Sugar (Cube)", Calorie = 11, Picture = "\\FoodPhotos\\202.jpg", Status = Status.Created },
            new Nutrient { Id = 203, NutrientCategoryId = 13, Name = "Sugar ", Calorie = 387, Picture = "\\FoodPhotos\\203.jpg", Status = Status.Created },
            new Nutrient { Id = 204, NutrientCategoryId = 13, Name = "Sugar Brown", Calorie = 373, Picture = "\\FoodPhotos\\204.jpg", Status = Status.Created },
            new Nutrient { Id = 205, NutrientCategoryId = 6, Name = "Cheesecake", Calorie = 329, Picture = "\\FoodPhotos\\205.jpg", Status = Status.Created },
            new Nutrient { Id = 206, NutrientCategoryId = 6, Name = "Muffin", Calorie = 400, Picture = "\\FoodPhotos\\206.jpg", Status = Status.Created },
            new Nutrient { Id = 207, NutrientCategoryId = 8, Name = "Milk", Calorie = 155, Picture = "\\FoodPhotos\\207.jpg", Status = Status.Created },
            new Nutrient { Id = 208, NutrientCategoryId = 8, Name = "Milk(Non-Fat)", Calorie = 87, Picture = "\\FoodPhotos\\208.jpg", Status = Status.Created },
            new Nutrient { Id = 209, NutrientCategoryId = 6, Name = "Brownie", Calorie = 230, Picture = "\\FoodPhotos\\209.jpg", Status = Status.Created },
            new Nutrient { Id = 210, NutrientCategoryId = 8, Name = "Feta Cheese", Calorie = 264, Picture = "\\FoodPhotos\\210.jpg", Status = Status.Created },
            new Nutrient { Id = 211, NutrientCategoryId = 8, Name = "Cheddar Cheese", Calorie = 402, Picture = "\\FoodPhotos\\211.jpg", Status = Status.Created },
            new Nutrient { Id = 212, NutrientCategoryId = 8, Name = "Mozzarella Cheese", Calorie = 280, Picture = "\\FoodPhotos\\212.jpg", Status = Status.Created },
            new Nutrient { Id = 213, NutrientCategoryId = 8, Name = "Parmesan Cheese", Calorie = 430, Picture = "\\FoodPhotos\\213.jpg", Status = Status.Created },
            new Nutrient { Id = 214, NutrientCategoryId = 8, Name = "Cream Cheese", Calorie = 342, Picture = "\\FoodPhotos\\214.jpg", Status = Status.Created },
            new Nutrient { Id = 215, NutrientCategoryId = 8, Name = "Goat Cheese", Calorie = 364, Picture = "\\FoodPhotos\\215.jpg", Status = Status.Created },
            new Nutrient { Id = 216, NutrientCategoryId = 3, Name = "Coke", Calorie = 98, Picture = "\\FoodPhotos\\216.jpg", Status = Status.Created },
            new Nutrient { Id = 217, NutrientCategoryId = 3, Name = "Coke Zero", Calorie = 1, Picture = "\\FoodPhotos\\217.jpg", Status = Status.Created },
            new Nutrient { Id = 218, NutrientCategoryId = 3, Name = "Americano", Calorie = 2, Picture = "\\FoodPhotos\\218.jpg", Status = Status.Created },
            new Nutrient { Id = 219, NutrientCategoryId = 3, Name = "Espresso", Calorie = 2, Picture = "\\FoodPhotos\\219.jpg", Status = Status.Created },
            new Nutrient { Id = 220, NutrientCategoryId = 3, Name = "Cappuccino", Calorie = 70, Picture = "\\FoodPhotos\\220.jpg", Status = Status.Created },
            new Nutrient { Id = 221, NutrientCategoryId = 3, Name = "Latte", Calorie = 120, Picture = "\\FoodPhotos\\221.jpg", Status = Status.Created },
            new Nutrient { Id = 222, NutrientCategoryId = 3, Name = "Mocha", Calorie = 210, Picture = "\\FoodPhotos\\222.jpg", Status = Status.Created },
            new Nutrient { Id = 223, NutrientCategoryId = 3, Name = "Iced Latte", Calorie = 70, Picture = "\\FoodPhotos\\223.jpg", Status = Status.Created },
            new Nutrient { Id = 224, NutrientCategoryId = 3, Name = "Iced Mocha", Calorie = 180, Picture = "\\FoodPhotos\\224.jpg", Status = Status.Created },
            new Nutrient { Id = 225, NutrientCategoryId = 3, Name = "Frappuccino", Calorie = 260, Picture = "\\FoodPhotos\\225.jpg", Status = Status.Created },
            new Nutrient { Id = 226, NutrientCategoryId = 5, Name = "Chocolate(Bitter)", Calorie = 630, Picture = "\\FoodPhotos\\226.jpg", Status = Status.Created },
            new Nutrient { Id = 227, NutrientCategoryId = 5, Name = "Chocolate(Milk)", Calorie = 542, Picture = "\\FoodPhotos\\227.jpg", Status = Status.Created },
            new Nutrient { Id = 228, NutrientCategoryId = 5, Name = "Chocolate(White)", Calorie = 557, Picture = "\\FoodPhotos\\228.jpg", Status = Status.Created },
            new Nutrient { Id = 229, NutrientCategoryId = 11, Name = "Ground Meat", Calorie = 260, Picture = "\\FoodPhotos\\229.jpg", Status = Status.Created },
            new Nutrient { Id = 230, NutrientCategoryId = 11, Name = "Meatball", Calorie = 65, Picture = "\\FoodPhotos\\230.jpg", Status = Status.Created },
            new Nutrient { Id = 231, NutrientCategoryId = 3, Name = "Mineral Water", Calorie = 1, Picture = "\\FoodPhotos\\231.jpg", Status = Status.Created },
            new Nutrient { Id = 232, NutrientCategoryId = 13, Name = "Olive Oil", Calorie = 119, Picture = "\\FoodPhotos\\232.jpg", Status = Status.Created },
            new Nutrient { Id = 233, NutrientCategoryId = 13, Name = "Canola Oil", Calorie = 124, Picture = "\\FoodPhotos\\233.jpg", Status = Status.Created },
            new Nutrient { Id = 234, NutrientCategoryId = 13, Name = "Sunflower Oil", Calorie = 120, Picture = "\\FoodPhotos\\234.jpg", Status = Status.Created },
            new Nutrient { Id = 235, NutrientCategoryId = 13, Name = "Sesame Oil", Calorie = 120, Picture = "\\FoodPhotos\\235.jpg", Status = Status.Created },
            new Nutrient { Id = 236, NutrientCategoryId = 13, Name = "Corn Oil", Calorie = 122, Picture = "\\FoodPhotos\\236.jpg", Status = Status.Created },
            new Nutrient { Id = 237, NutrientCategoryId = 13, Name = "Flour", Calorie = 364, Picture = "\\FoodPhotos\\237.jpg", Status = Status.Created },
            new Nutrient { Id = 238, NutrientCategoryId = 11, Name = "Sunnyside-up", Calorie = 95, Picture = "\\FoodPhotos\\238.jpg", Status = Status.Created },
            new Nutrient { Id = 239, NutrientCategoryId = 4, Name = "Red Wine", Calorie = 15, Picture = "\\FoodPhotos\\239.jpg", Status = Status.Created },
            new Nutrient { Id = 240, NutrientCategoryId = 4, Name = "White Wine", Calorie = 125, Picture = "\\FoodPhotos\\240.jpg", Status = Status.Created },
            new Nutrient { Id = 241, NutrientCategoryId = 4, Name = "Beer", Calorie = 155, Picture = "\\FoodPhotos\\241.jpg", Status = Status.Created },
            new Nutrient { Id = 242, NutrientCategoryId = 4, Name = "Champagne", Calorie = 95, Picture = "\\FoodPhotos\\242.jpg", Status = Status.Created },
            new Nutrient { Id = 243, NutrientCategoryId = 4, Name = "Vodka", Calorie = 96, Picture = "\\FoodPhotos\\243.jpg", Status = Status.Created },
            new Nutrient { Id = 244, NutrientCategoryId = 4, Name = "Rum", Calorie = 97, Picture = "\\FoodPhotos\\244.jpg", Status = Status.Created },
            new Nutrient { Id = 245, NutrientCategoryId = 4, Name = "Whiskey", Calorie = 98, Picture = "\\FoodPhotos\\245.jpg", Status = Status.Created },
            new Nutrient { Id = 246, NutrientCategoryId = 4, Name = "Tequila", Calorie = 98, Picture = "\\FoodPhotos\\246.jpg", Status = Status.Created },
            new Nutrient { Id = 247, NutrientCategoryId = 4, Name = "Gin", Calorie = 96, Picture = "\\FoodPhotos\\247.jpg", Status = Status.Created },
            new Nutrient { Id = 248, NutrientCategoryId = 9, Name = "Trout", Calorie = 119, Picture = "\\FoodPhotos\\248.jpg", Status = Status.Created },
            new Nutrient { Id = 249, NutrientCategoryId = 9, Name = "Halibut", Calorie = 111, Picture = "\\FoodPhotos\\249.jpg", Status = Status.Created },
            new Nutrient { Id = 250, NutrientCategoryId = 9, Name = "Sardines", Calorie = 208, Picture = "\\FoodPhotos\\250.jpg", Status = Status.Created },
            new Nutrient { Id = 251, NutrientCategoryId = 9, Name = "Mackerel", Calorie = 305, Picture = "\\FoodPhotos\\251.jpg", Status = Status.Created },
            new Nutrient { Id = 252, NutrientCategoryId = 5, Name = "Snickers", Calorie = 280, Picture = "\\FoodPhotos\\252.jpg", Status = Status.Created },
            new Nutrient { Id = 253, NutrientCategoryId = 5, Name = "Twix", Calorie = 250, Picture = "\\FoodPhotos\\253.jpg", Status = Status.Created },
            new Nutrient { Id = 254, NutrientCategoryId = 5, Name = "Kit Kat", Calorie = 210, Picture = "\\FoodPhotos\\254.jpg", Status = Status.Created }
        );
        }
    }
}
